title: Ilya Natarov
description: Welcome to my webpage! 
theme: just-the-docs
lang: es-ES

url: https://nottaroff.github.io

#Color theme
color_scheme: dark

#Web Logo
logo: "/media/home-logo.png"

favicon_ico: "/media/n-web-logo.png"


callouts:
  warning:
    title: Warning
    color: red
  
  important:
    title: Work in progress
    color: blue
    opacity: 0.3

  work:
    title: Work in progress
    color: yellow
    opacity: 0.3

  detail:
    color: blue
    opacity: 0.2

  importance:
    color: red
    opacity: 0.2
